version: "3.10"
services:
  django:
    build: .
#    volumes:
#      - ".:/plotly_doc/home"
    links:
      - selenium
    ports:
      - 8222:8222
#
  selenium:
    environment:
      - VNC_NO_PASSWORD=1 # Don't ask for a password
    image: selenium/standalone-chrome
    ports:
      - 7900:7900
