version: "3.10"
services:
  django:
    build: .
    volumes:
      - ".:/plotly_doc/home"
    links:
      - selenium
    ports:
      - 8222:8222

  selenium:
    environment:
      - VNC_NO_PASSWORD=1 # Don't ask for a password
    image: selenium/standalone-chrome
    ports:
      - 7900:7900
  chrome:
    image: selenium/standalone-chrome

    volumes:
      - /home/qa/Downloads:/home/bilgi/Downloads
  firefox:
    image: selenium/standalone-chrome

    volumes:
      - /home/qa/Downloads:/home/bilgi/Downloads
  web:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
      - ./tempDownload:/home/seluser/Downloads
    ports:
      - 4446:4444
      - 0.0.0.0:9222:9222
